---Composite Index on Join + Filter

SELECT * FROM ORDERS;

SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME='ORDERS';

CREATE INDEX IDX_ORDERSTATUS_DATE ON ORDERS(O_ORDERSTATUS,O_ORDERDATE);

SELECT /*+ INDEX(ORDERS IDX_ORDERSTATUS_DATE) */
 O_ORDERPRIORITY,COUNT(*) FROM ORDERS
WHERE O_ORDERSTATUS='F'
AND O_ORDERDATE  BETWEEN DATE '1995-01-01' AND DATE '1995-06-30'
GROUP BY o_orderpriority
ORDER BY O_ORDERPRIORITY;


---=======
EXPLAIN PLAN FOR 
SELECT /*+ INDEX(ORDERS IDX_ORDERSTATUS_DATE) */
 O_ORDERPRIORITY,COUNT(*) FROM ORDERS
WHERE O_ORDERSTATUS='F'
AND O_ORDERDATE  BETWEEN DATE '1995-01-01' AND DATE '1995-06-30'
GROUP BY o_orderpriority
ORDER BY O_ORDERPRIORITY;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);