SELECT /*+ INDEX (orders idx_orders_orderdate) */
    O_ORDERPRIORITY,
    COUNT(*) AS ORDER_COUNT
FROM 
    ORDERS
WHERE
    O_ORDERDATE >= DATE '1995-01-01'
AND
    O_ORDERDATE < DATE '1996-01-01'
GROUP BY 
    O_ORDERPRIORITY
ORDER BY
    O_ORDERPRIORITY;
    
SELECT INDEX_NAME,INDEX_TYPE FROM USER_INDEXES WHERE TABLE_NAME='ORDERS';

EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => 'TPCH', tabname => 'ORDERS');

--=========
SELECT COUNT(*)
    FROM ORDERS 
    WHERE o_orderdate >= DATE '1995-01-01'
  AND o_orderdate < DATE '1996-01-01';
  
  SELECT COUNT(*) FROM ORDERS;