 ---Function-Based Index on UPPER(c_name)
 
SELECT * FROM CUSTOMER
    WHERE UPPER(C_NAME)='AUTOMOBILE COMPANY';
    
SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME='CUSTOMER';

CREATE INDEX IDX_UPPER_CNAME ON CUSTOMER(UPPER(C_NAME));

---EXECUTION PLAN
EXPLAIN PLAN FOR
SELECT * 
FROM customer 
WHERE UPPER(c_name) = 'AUTOMOBILE COMPANY';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
