---Virtual Column + Index

SELECT * FROM ORDERS;

ALTER TABLE ORDERS ADD O_ORDERYEAR AS (EXTRACT(YEAR FROM O_ORDERDATE));

SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME='ORDERS';

CREATE INDEX IDX_ORDERYEAR ON ORDERS(O_ORDERYEAR);

SELECT COUNT(*) FROM ORDERS WHERE O_ORDERYEAR=1995;

--===
EXPLAIN PLAN FOR
SELECT COUNT(*) FROM orders WHERE o_orderyear = 1995;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);