CREATE OR REPLACE FUNCTION GET_BONUS(EMP_ID NUMBER)
RETURN NUMBER
IS
    EMP_SAL NUMBER;
    BONUS NUMBER;
BEGIN
    SELECT SAL INTO EMP_SAL FROM EMP_LARGE WHERE EMPNO=EMP_ID;
    
    BONUS := EMP_SAL*0.10;
    RETURN BONUS;
END;

SELECT GET_BONUS(1234) FROM DUAL;