
---FUNCTION TO GET EMPLOYEE NAME
CREATE OR REPLACE FUNCTION GET_NAME(F_EMPNO NUMBER)
RETURN VARCHAR2
IS
    EMP_NAME VARCHAR2(50);
  BEGIN
    SELECT ENAME INTO EMP_NAME FROM EMP_LARGE WHERE EMPNO=F_EMPNO;
    RETURN EMP_NAME;
    END;
    
SELECT GET_NAME(1234) FROM DUAL;