 ---Function to Increase Salary of an Employee (Using IN OUT
 CREATE OR REPLACE FUNCTION INCREASE_SAL(EMP_ID NUMBER,INCREMENT NUMBER)
 RETURN NUMBER
 IS
    EMP_SAL NUMBER;
BEGIN
    SELECT SAL INTO EMP_SAL FROM EMP_LARGE WHERE EMPNO=EMP_ID;
    EMP_SAL :=EMP_SAL+INCREMENT;
    
    UPDATE EMP_LARGE SET SAL=EMP_SAL WHERE EMPNO=EMP_ID;
    COMMIT;
    
    RETURN EMP_SAL;
    END;
    
    SELECT INCREASE_SAL(1234,500) FROM DUAL;