DECLARE
    TYPE EMP_CURSOR_TYPE  IS REF CURSOR RETURN EMP_LARGE%ROWTYPE;
    EMP_CURSOR EMP_CURSOR_TYPE;
    EMP_RECORD EMP_LARGE%ROWTYPE;
BEGIN
    OPEN EMP_CURSOR FOR SELECT * FROM EMP_LARGE WHERE DEPTNO=20;
    
    LOOP
        FETCH EMP_CURSOR INTO EMP_RECORD;
        EXIT WHEN EMP_CURSOR%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE('Emp ID: ' || emp_record.EMPNO || ' - Name: ' || emp_record.ENAME);
    END LOOP;
    
    CLOSE emp_cursor;
END;
/
    