----If an employee’s DEPTNO is NULL, assign them to DEPTNO = 10 by default.
CREATE OR REPLACE TRIGGER auto_assign_dept
BEFORE INSERT ON EMP_LARGE
FOR EACH ROW
BEGIN
    IF :NEW.DEPTNO IS NULL THEN
        :NEW.DEPTNO := 10;
    END IF;
END;
/

---=========
INSERT INTO EMP_LARGE (EMPNO, ENAME, SAL) VALUES (1100, 'ALEX', 4500);
SELECT * FROM EMP_LARGE WHERE EMPNO = 1100;
