 CREATE OR REPLACE TRIGGER SHASHI.BEFORE_INSERT_EMP
BEFORE INSERT
ON SHASHI.EMP_LARGE
FOR EACH ROW


BEGIN
    IF :NEW.SAL<2000 THEN
    RAISE_APPLICATION_ERROR(-20001, 'SAL MUST BE AT LEAST 2000!');
    END IF;
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END BEFORE_INSERT_EMP;



---======
INSERT INTO EMP_LARGE(EMPNO,ENAME,SAL) VALUES(1236,'VAMSHI',800);

DELETE FROM EMP_LARGE WHERE EMPNO=1236;

SELECT * FROM EMP_LARGE WHERE EMPNO=1236;