----Ensure that employees cannot have a salary more than 50000.
CREATE OR REPLACE TRIGGER ENFORCE_MAX_SAL
BEFORE INSERT OR UPDATE ON EMP_LARGE
FOR EACH ROW
BEGIN
     IF :NEW.SAL > 50000 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Salary cannot exceed 50,000');
    END IF;
END;

---==============TESTING
UPDATE EMP_LARGE SET SAL=51000 WHERE EMPNO=111;