---Prevent deleting an employee who is a Manager (JOB = 'MANAGER').
CREATE OR REPLACE TRIGGER PREVENT_MANAGER_DELETION
BEFORE DELETE ON EMP_LARGE
FOR EACH ROW
BEGIN
    IF :OLD.JOB= 'MANAGER' THEN
    RAISE_APPLICATION_ERROR(-20002, 'Managers cannot be deleted');
    END IF;
END;

------------TESTING
DELETE FROM EMP_LARGE WHERE JOB='MANAGER';