CREATE OR REPLACE TRIGGER ROW_LEVEL_DELETE_RESTRICT
BEFORE DELETE ON EMP_LARGE
FOR EACH ROW
BEGIN
    IF :OLD.DEPTNO=10 THEN
     RAISE_APPLICATION_ERROR(-20002, 'Employees in department 10 cannot be deleted!');
    END IF;
END;

---==================
DELETE FROM EMP_LARGE WHERE DEPTNO=10;