--- Statement-Level Triggers

CREATE TABLE SAL_LOG(LOG_MSG VARCHAR2(100),LOG_DATE DATE);

SELECT * FROM SAL_LOG;

DESC SAL_LOG;

-----===========
CREATE OR REPLACE TRIGGER STMT_LEVEL_UPDATE_LOG
AFTER UPDATE OF SAL ON EMP_LARGE
BEGIN
    INSERT INTO SAL_LOG(LOG_MSG, LOG_DATE)
    VALUES ('Salary updated for employees', SYSDATE);
END;


TESTING----===========

UPDATE EMP_LARGE SET SAL=SAL+500 WHERE DEPTNO=20;

SELECT * FROM SAL_LOG;