LOAD DATA
INFILE 'employees_bad.csv'
BADFILE 'EMP_BAD_RECORDS.BAD'
DISCARDFILE 'EMP_DISCARD.LOG'
INTO TABLE EMP_BAD
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
	EMPNO,
	FIRST_NAME,
	LAST_NAME,
	SALARY	
)