
  CREATE TABLE "TPCH"."PART" 
   (	"P_PARTKEY" NUMBER, 
	"P_NAME" VARCHAR2(55), 
	"P_MFGR" CHAR(25), 
	"P_BRAND" CHAR(10), 
	"P_TYPE" VARCHAR2(25), 
	"P_SIZE" NUMBER, 
	"P_CONTAINER" CHAR(10), 
	"P_RETAILPRICE" NUMBER(12,2), 
	"P_COMMENT" VARCHAR2(23), 
	 PRIMARY KEY ("P_PARTKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 