
  CREATE TABLE "TPCH"."SUPPLIER" 
   (	"S_SUPPKEY" NUMBER, 
	"S_NAME" CHAR(25), 
	"S_ADDRESS" VARCHAR2(40), 
	"S_NATIONKEY" NUMBER, 
	"S_PHONE" CHAR(15), 
	"S_ACCTBAL" NUMBER(12,2), 
	"S_COMMENT" VARCHAR2(101), 
	 PRIMARY KEY ("S_SUPPKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 