--- Create a procedure to fetch employee details by EMPNO.
CREATE OR REPLACE PROCEDURE GET_EMP_DETAILS( EMP_ID IN NUMBER)
IS
    V_ENAME VARCHAR2(20);
    V_SAL EMP_LARGE.SAL%TYPE;
BEGIN
    SELECT ENAME,SAL INTO V_ENAME,V_SAL FROM EMP_LARGE WHERE EMPNO=EMP_ID;
    
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME: ' || V_ENAME);
    DBMS_OUTPUT.PUT_LINE('SALARY: '||V_SAL);
    END;
    /
    

BEGIN
    GET_EMP_DETAILS(1234);
    END;
    