CREATE OR REPLACE PROCEDURE INCREASE_SALARY (
    EMP_ID IN NUMBER,  
    NEW_SALARY OUT NUMBER 
)
IS
    EMP_SAL NUMBER;
BEGIN
   SELECT SAL INTO EMP_SAL FROM EMP_LARGE WHERE EMPNO=EMP_ID;
   NEW_SALARY:=EMP_SAL*1.10;  

    UPDATE EMP_LARGE 
    SET SAL = NEW_SALARY 
    WHERE EMPNO = EMP_ID;

    COMMIT; 
END;

--===========
DECLARE 
    UPDATED_SAL NUMBER;
BEGIN
    INCREASE_SALARY(101, UPDATED_SAL);
    DBMS_OUTPUT.PUT_LINE('Updated Salary: ' || UPDATED_SAL);
END;
