----Return the salary of an employee based on EMPNO.
CREATE OR REPLACE PROCEDURE EMP_SAL
(
    EMP_ID IN NUMBER,
    EMP_SALARY OUT NUMBER
)
IS
BEGIN
    SELECT SAL INTO EMP_SALARY FROM EMP_LARGE WHERE EMPNO=EMP_ID;
    DBMS_OUTPUT.PUT_LINE('EMP SAL: ' || EMP_SALARY);
    END;


--- CALLING PROCEDURE    
DECLARE
    SALARY NUMBER;    
BEGIN
    EMP_SAL(1234,SALARY);
    END;