CREATE CLUSTER DEPT_EMP(DNO NUMBER(4));

CREATE INDEX CI ON CLUSTER DEPT_EMP;

CREATE TABLE DEPT44(DNO NUMBER(4),DNAME VARCHAR2(10)) CLUSTER DEPT_EMP(DNO);

INSERT INTO DEPT44 VALUES(10,'D1');
INSERT INTO DEPT44 VALUES(20,'D2');

CREATE TABLE EMP44(ENAME VARCHAR2(10),DNO NUMBER(4)) CLUSTER DEPT_EMP(DNO);

INSERT INTO EMP44 VALUES('SHASHI',10);

INSERT INTO EMP44 VALUES('KIRAN',20);

SELECT * FROM DEPT44;

SELECT * FROM EMP44;

SELECT ROWID FROM DEPT44;

SELECT ROWID FROM EMP44;

DESC USER_CLUSTERS;

SELECT CLUSTER_NAME FROM USER_CLUSTERS;

DESC USER_TABLES;

SELECT TABLE_NAME FROM USER_TABLES WHERE CLUSTER_NAME='DEPT_EMP';


SELECT D.DNO,D.DNAME,E.ENAME FROM DEPT44 D JOIN EMP44 E ON D.DNO=E.DNO;

EXPLAIN PLAN FOR
SELECT D.DNO,D.DNAME,E.ENAME FROM DEPT44 D JOIN EMP44 E ON D.DNO=E.DNO;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);