SELECT * FROM EMP2;

-- FETCH SINGLE ROW

DECLARE CURSOR C1 IS SELECT EMPNO,ENAME,SAL FROM EMP2;
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
BEGIN
OPEN C1;
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
CLOSE C1;
END;
/

--EX -2 MULTIPLE ROWS FETCH

DECLARE CURSOR C1 IS SELECT EMPNO,ENAME,SAL FROM EMP2;
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
BEGIN
OPEN C1;
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
CLOSE C1;
END;
/

--EX-3 SIMPLE LOOP

DECLARE CURSOR C1 IS SELECT EMPNO,ENAME,SAL FROM EMP2;
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
BEGIN
OPEN C1;
LOOP
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
END LOOP;
CLOSE C1;
END;
/

--while loop EX-4

DECLARE CURSOR C1 IS SELECT EMPNO,ENAME,SAL FROM EMP2;
V_EMPNO EMP.EMPNO%TYPE;
V_ENAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
BEGIN
OPEN C1;
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
while(C1%FOUND)
LOOP
DBMS_OUTPUT.PUT_LINE(V_EMPNO||','||V_ENAME||','||V_SAL);
FETCH C1 INTO V_EMPNO,V_ENAME,V_SAL;
END LOOP;
CLOSE C1;
END;
/