SET SERVEROUTPUT ON;
--EXAMPLE 1
DECLARE
MESSAGE VARCHAR2(20):='LEARNING PLSQL';
BEGIN
DBMS_OUTPUT.PUT_LINE('HI, '||MESSAGE);
END;
/

DECLARE
EMP_SAL EMP.SAL%TYPE;
BEGIN
SELECT SAL INTO EMP_SAL FROM EMP WHERE ENAME='SMITH';
DBMS_OUTPUT.PUT_LINE(EMP_SAL);
END;
/


DECLARE
A NUMBER(3):=10;
BEGIN
IF(A<20) THEN
DBMS_OUTPUT.PUT_LINE('A IS LESS THAN 20');
ELSE 
DBMS_OUTPUT.PUT_LINE('A IS GREATER THAN 20');
END IF;
DBMS_OUTPUT.PUT_LINE('VALUE OF A IS: '||A);
END;
/