CREATE TABLE SOURCE_TABLE(SNO NUMBER(3),SNAME VARCHAR2(10),LOC VARCHAR2(10));

CREATE TABLE DESTINATION_TABLE(SNO NUMBER(3),SNAME VARCHAR2(10),LOC VARCHAR2(10));

INSERT INTO SOURCE_TABLE VALUES(&SNO,'&SNAME','&LOC');

SELECT * FROM SOURCE_TABLE;

INSERT INTO DESTINATION_TABLE VALUES(&SNO,'&SNAME','&LOC');

MERGE INTO DESTINATION_TABLE D USING SOURCE_TABLE S ON (D.SNO=S.SNO)
WHEN MATCHED THEN
UPDATE SET D.SNAME=S.SNAME,D.LOC=S.LOC
WHEN NOT MATCHED THEN
INSERT (D.SNO,D.SNAME,D.LOC) VALUES(S.SNO,S.SNAME,S.LOC);

SELECT * FROM DESTINATION_TABLE;