SELECT index_name, table_name, column_name
FROM user_ind_columns
WHERE table_name = 'EMP_LARGE';

SELECT * FROM EMP_LARGE;

explain plan for
SELECT * FROM EMP_LARGE WHERE ENAME='Employee 1001';

select * from table(dbms_xplan.display);
--========================================
ALTER SESSION SET SQL_TRACE = TRUE;

select * from emp_large where deptno=10;

ALTER SESSION SET SQL_TRACE = FALSE;

SELECT value FROM v$diag_info WHERE name = 'Default Trace File';
--=====================================

INSERT INTO EMP_LARGE(EMPNO,ENAME,SAL,DEPTNO) 
VALUES(1235,'UPENDER',5555,10);
COMMIT;

EXPLAIN PLAN FOR
SELECT * FROM EMP_MV WHERE EMPNO=1234;

EXPLAIN PLAN FOR
SELECT * FROM EMP_MV1 WHERE EMPNO=1235;;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

SELECT * FROM EMP_LARGE WHERE EMPNO=1235;

EXEC DBMS_MVIEW.REFRESH('EMP_MV1','F');

SELECT MVIEW_NAME, REFRESH_MODE, REFRESH_METHOD 
FROM USER_MVIEWS;
=============================================
--EXPLAIN PLAN FOR
SELECT E.ENAME,E.JOB,D.DNAME FROM EMP_LARGE E JOIN DEPT_LARGE D ON
E.DEPTNO=D.DEPTNO;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

SELECT ENAME, LEVEL 
FROM EMP_LARGE 
START WITH MGR IS NULL 
CONNECT BY PRIOR EMPNO = MGR;
