SET SERVEROUTPUT ON;

SELECT * FROM EMP;
INSERT INTO EMP VALUES
        (7369, 'SMITH',  'CLERK',     7902,
        TO_DATE('17-DEC-1980', 'DD-MON-YYYY'),  800, NULL, 20);
INSERT INTO EMP VALUES
        (7499, 'ALLEN',  'SALESMAN',  7698,
        TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600,  300, 30);
INSERT INTO EMP VALUES
        (7521, 'WARD',   'SALESMAN',  7698,
        TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250,  500, 30);
INSERT INTO EMP VALUES
        (7566, 'JONES',  'MANAGER',   7839,
        TO_DATE('2-APR-1981', 'DD-MON-YYYY'),  2975, NULL, 20);
INSERT INTO EMP VALUES
        (7654, 'MARTIN', 'SALESMAN',  7698,
        TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30);
INSERT INTO EMP VALUES
        (7698, 'BLAKE',  'MANAGER',   7839,
        TO_DATE('1-MAY-1981', 'DD-MON-YYYY'),  2850, NULL, 30);
INSERT INTO EMP VALUES
        (7782, 'CLARK',  'MANAGER',   7839,
        TO_DATE('9-JUN-1981', 'DD-MON-YYYY'),  2450, NULL, 10);
INSERT INTO EMP VALUES
        (7788, 'SCOTT',  'ANALYST',   7566,
        TO_DATE('09-DEC-1982', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP VALUES
        (7839, 'KING',   'PRESIDENT', NULL,
        TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10);
INSERT INTO EMP VALUES
        (7844, 'TURNER', 'SALESMAN',  7698,
        TO_DATE('8-SEP-1981', 'DD-MON-YYYY'),  1500,    0, 30);
INSERT INTO EMP VALUES
        (7876, 'ADAMS',  'CLERK',     7788,
        TO_DATE('12-JAN-1983', 'DD-MON-YYYY'), 1100, NULL, 20);
INSERT INTO EMP VALUES
        (7900, 'JAMES',  'CLERK',     7698,
        TO_DATE('3-DEC-1981', 'DD-MON-YYYY'),   950, NULL, 30);
INSERT INTO EMP VALUES
        (7902, 'FORD',   'ANALYST',   7566,
        TO_DATE('3-DEC-1981', 'DD-MON-YYYY'),  3000, NULL, 20);
INSERT INTO EMP VALUES
        (7934, 'MILLER', 'CLERK',     7782,
        TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10);
    
    COMMIT;

CREATE VIEW EMP1 AS
SELECT * FROM EMP;

SELECT * FROM EMP1;


CREATE SEQUENCE EMP_SEQ 
START WITH 7935
INCREMENT BY 1
NOCYCLE
NOCACHE;

--PROCEDURE FOR INSERT INTO EMP
CREATE OR REPLACE PROCEDURE INSERT_EMP(NEW_EMPNO OUT NUMBER,ENAME IN VARCHAR2,SAL IN NUMBER,INSERTED_SAL OUT NUMBER) IS
BEGIN
SELECT EMP_SEQ.NEXTVAL INTO NEW_EMPNO FROM DUAL;
INSERTED_SAL:=SAL;
INSERT INTO EMP1(EMPNO,ENAME,SAL) VALUES(NEW_EMPNO,ENAME,SAL);
COMMIT;
DBMS_OUTPUT.PUT_LINE('EMP DETAILS INSERTED SUCCESSFULLY! EMPNO: '||NEW_EMPNO||',SALARY: '||INSERTED_SAL);
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END;
/

EXECUTE INSERT_EMP(1234,'SHASHI');
EXECUTE INSERT_EMP(1235,'KIRAN');

BEGIN
INSERT_EMP(1236,'UPPI',2500);
END;
/
--    INSERTION INTO EMP1 WITH EMP_SEQ
DECLARE
V_EMPNO NUMBER;
V_SALARY NUMBER;
BEGIN
INSERT_EMP(V_EMPNO,'PADMA',4100,V_SALARY);
DBMS_OUTPUT.PUT_LINE('NEW EMP ID: '||V_EMPNO||',SALARY: '||V_SALARY);
END;
/


DELETE FROM EMP1 WHERE ENAME='SHASHI';

--EXAMPLE-1
--Task: Write a PL/SQL block to calculate the sum of numbers from 1 to 10.
DECLARE
TOTAL NUMBER:=0;
BEGIN
FOR i IN 1..10 LOOP
TOTAL := TOTAL+i;
END LOOP;
DBMS_OUTPUT.PUT_LINE('SUM: '||TOTAL);
END;
/

--Problem 2: Second Highest Salary
--Task: Write a PL/SQL block to find the second highest salary in a table named employees
DECLARE
SECOND_HIGHEST NUMBER;
BEGIN
SELECT MAX(SAL) INTO SECOND_HIGHEST FROM EMP1
WHERE SAL<(SELECT MAX(SAL) FROM EMP1);
DBMS_OUTPUT.PUT_LINE('SECOND HIGHEST SALLARY: '||SECOND_HIGHEST);
END;
/

--Problem 3: Delete Old Records
--Task: Create a stored procedure to delete records older than a specific date from the employees table
CREATE OR REPLACE PROCEDURE DELETE_OLD_EMP(CUTOFF_DATE IN DATE) IS
BEGIN
    DELETE FROM EMP1 WHERE HIREDATE<CUTOFF_DATE;
    COMMIT;
END;
/

BEGIN
DELETE_OLD_EMP(TO_DATE('2022-01-01', 'YYYY-MM-DD'));
END;
/
ROLLBACK;

DESC USER_PROCEDURES;

SELECT OBJECT_NAME,PROCEDURE_NAME FROM USER_PROCEDURES WHERE OBJECT_TYPE='PROCEDURE';

DESC USER_SOURCE;

SELECT TEXT FROM USER_SOURCE WHERE NAME='INSERT_EMP'
ORDER BY LINE;

DESC USER_OBJECTS;

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS 
FROM USER_OBJECTS 
WHERE OBJECT_TYPE = 'PROCEDURE';

