CREATE TABLE TEST2
(
    ID INT,
    SALE_DATE DATE,
    SALES NUMBER(4)
);

INSERT INTO TEST2 VALUES(&ID,'&SALE_DATE',&SALES);

SELECT * FROM TEST2;

SELECT ID,SALE_DATE,SALES,SUM(SALES) OVER(ORDER BY SALE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND
CURRENT ROW) AS RUNNING_SUM FROM TEST2;

SELECT ID,SALE_DATE,SALES,SUM(SALES) OVER(ORDER BY SALE_DATE)AS RUNNING_SUM FROM TEST2;

