SELECT empno,ename 
FROM emp_large 
WHERE deptno IS NULL;

SELECT empno,ename,hiredate
FROM emp_large 
WHERE hiredate >= ADD_MONTHS(SYSDATE, -36);

ALTER USER SHASHI QUOTA UNLIMITED ON USERS;

GRANT ALL PRIVILEGES TO SHASHI;

GRANT CONNECT, RESOURCE TO SHASHI;
GRANT DBA TO SHASHI;


SELECT USERNAME FROM ALL_USERS;

GRANT CREATE SESSION TO SHASHI;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE SYNONYM TO SHASHI;
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE TO SHASHI;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE TO SHASHI;
GRANT CREATE ANY PROCEDURE, EXECUTE ANY PROCEDURE, DROP ANY PROCEDURE TO SHASHI;
GRANT CREATE ANY VIEW, DROP ANY VIEW TO SHASHI;
GRANT UNLIMITED TABLESPACE TO SHASHI;



show con_name;

SHOW PDBS;

ALTER SESSION SET CONTAINER = ORCLPDB;
