SELECT
    L_ORDERKEY,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE,
    O_ORDERDATE,
    O_SHIPPRIORITY
FROM
    CUSTOMER
JOIN
    ORDERS ON C_CUSTKEY = O_CUSTKEY
JOIN
    LINEITEM ON L_ORDERKEY = O_ORDERKEY
WHERE
    C_MKTSEGMENT = 'AUTOMOBILE'
    AND O_ORDERDATE < DATE '1995-03-15'
    AND L_SHIPDATE > DATE '1995-03-15'
GROUP BY
    L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY
    REVENUE DESC;


--==============(INDEXES)
CREATE INDEX IDX_CUSTOMER_MKTSEGMENT ON CUSTOMER(C_MKTSEGMENT);

-- Helps filter O_ORDERDATE and join faster
CREATE INDEX IDX_ORDERS_CUSTKEY_DATE ON ORDERS(O_CUSTKEY, O_ORDERDATE);

-- Helps filter L_SHIPDATE and join to ORDERS
CREATE INDEX IDX_LINEITEM_ORDERKEY_SHIPDATE ON LINEITEM(L_ORDERKEY, L_SHIPDATE);


--===========
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'CUSTOMER');
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'ORDERS');
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'LINEITEM');
END;
