SELECT INDEX_NAME,INDEX_TYPE FROM USER_INDEXES WHERE TABLE_NAME='ORDERS';

CREATE INDEX IDX_INVISIBLE_ORDERSTATUS ON ORDERS(O_ORDERSTATUS) INVISIBLE;

SELECT COUNT(*) FROM ORDERS
    WHERE O_ORDERSTATUS='F';
    
EXPLAIN PLAN FOR
SELECT COUNT(*) FROM orders WHERE o_orderstatus = 'F';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

--====
ALTER SESSION SET optimizer_use_invisible_indexes = TRUE;

EXPLAIN PLAN FOR
SELECT COUNT(*) FROM orders WHERE o_orderstatus = 'F';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
