CREATE OR REPLACE PACKAGE EMP_PKG
IS
    PROCEDURE GET_EMP_NAME(TEMPNO EMP_LARGE.EMPNO%TYPE);
END EMP_PKG;

----BODY
CREATE OR REPLACE PACKAGE BODY EMP_PKG
IS
    PROCEDURE GET_EMP_NAME(TEMPNO EMP_LARGE.EMPNO%TYPE)
    IS
        VENAME EMP_LARGE.ENAME%TYPE;
    BEGIN
        SELECT ENAME INTO VENAME FROM EMP_LARGE WHERE EMPNO=TEMPNO;
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME: '||VENAME);
    END GET_EMP_NAME;
END EMP_PKG;

---============
EXEC EMP_PKG.GET_EMP_NAME(1234);