CREATE OR REPLACE PACKAGE EMP_UTIL AS
    PROCEDURE PUBLIC_PROC;
END EMP_UTIL;

---======BODY
CREATE OR REPLACE PACKAGE BODY EMP_UTIL AS
    PROCEDURE PRIVATE_PROC IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('THIS IS A PRIVATE PROCEDURE');
        END PRIVATE_PROC;
      
    PROCEDURE PUBLIC_PROC IS
    BEGIN
    DBMS_OUTPUT.PUT_LINE('Calling private procedure...');
        PRIVATE_PROC;
    END PUBLIC_PROC;
END EMP_UTIL;


-------========
EXEC EMP_UTIL.PRIVATE_PROC;

EXEC EMP_UTIL.PUBLIC_PROC;